#!/usr/bin/env python3
"""Geometric QA for generated SVGs — catches 'correct data, ugly render'.

Checks per lab:
  G1  every node fully inside the 720x490 viewBox
  G2  no node-node bounding-box overlaps (extracted positions must not collide)
  G3  every data-link has both endpoints present as nodes
  G4  every port chip is within 90px of its owner node center (not floating)
  G5  port chips do not overlap each other
  G6  link lines do not cross a third node's bounding box (gross routing errors)
  G7  node label text fits the node box (name length vs node width)

Prints PASS/FAIL per lab per gate. Exit 1 if any FAIL.
"""
import json
import os
import re
import sys

# NOTE: qa_geometry runs WITHOUT Go — it can't read the topology structs
# directly. The expected node/link sets are passed in via a JSON manifest
# generated by the renderer (render --manifest). Without it, G0 is skipped.

GENERATED = "tools/topogen/generated"
POSITIONS = "tools/topogen/positions.json"
VIEW_W, VIEW_H = 720, 490
NODE_W, NODE_H = 140, 60
HOST_R = 30


def load_manifest():
    path = os.path.join(os.path.dirname(__file__), "manifest.json")
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def parse_svg(path):
    with open(path) as f:
        s = f.read()
    return s


def node_boxes(svg):
    """Return dict name -> (cx, cy, kind, half_w, half_h)."""
    nodes = {}
    # ALL node roles render inside <g data-node="NAME" data-role="..."> —
    # core/hub/attacker contain a rect, hosts contain a circle. Attacker
    # rects are nested inside a <g filter> so find the first rect/circle
    # within the group segment regardless of nesting.
    for m in re.finditer(r'<g data-node="([^"]+)"[^>]*data-role="([^"]+)"[^>]*>', svg):
        name, role = m.group(1), m.group(2)
        g_start = m.start()
        # group closes at the matching </g> — attacker groups have an inner
        # <g filter>...</g>, so scan until the group's own closing tag
        depth = 0
        g_end = None
        for mm in re.finditer(r'<g\b|</g>', svg[g_start:]):
            if mm.group(0) == '<g':
                depth += 1
            else:
                depth -= 1
                if depth == 0:
                    g_end = g_start + mm.end()
                    break
        seg = svg[g_start:g_end] if g_end else svg[g_start:g_start + 1000]
        rm = re.search(r'<rect x="(-?[\d.]+)" y="(-?[\d.]+)" width="(-?[\d.]+)" height="(-?[\d.]+)"', seg)
        cm = re.search(r'<circle cx="(-?[\d.]+)" cy="(-?[\d.]+)" r="(-?[\d.]+)"', seg)
        if rm:
            x, y, w, h = map(float, rm.groups())
            nodes[name] = (x + w / 2, y + h / 2, "rect", w / 2, h / 2)
        elif cm:
            cx, cy, r = map(float, cm.groups())
            if r >= 20:
                nodes[name] = (cx, cy, "circle", r, r)
    return nodes


def chips(svg):
    out = []
    for m in re.finditer(r'<g data-port="([^"]+)"[^>]*>\s*<rect x="(-?[\d.]+)" y="(-?[\d.]+)" width="(-?[\d.]+)" height="(-?[\d.]+)"', svg):
        name, x, y, w, h = m.group(1), *map(float, m.groups()[1:])
        out.append((name, x + w / 2, y + h / 2))
    return out


def links(svg):
    out = []
    for m in re.finditer(r'<g data-link="([^"]+)"', svg):
        out.append(m.group(1))
    return out


def main():
    manifest = load_manifest()
    fails = 0
    labs = sorted(int(f[:-4]) for f in os.listdir(GENERATED) if f.endswith(".svg"))
    for lab in labs:
        svg = parse_svg(os.path.join(GENERATED, f"{lab}.svg"))
        boxes = node_boxes(svg)
        chip_list = chips(svg)
        link_list = links(svg)
        problems = []

        # G0 completeness — every template node and link must exist in the
        # SVG. Without this, an empty chrome-only render passes all other
        # gates vacuously (the Lab 15 failure). Skipped if no manifest.
        if manifest is not None:
            exp = manifest.get(str(lab), {})
            exp_nodes = set(exp.get("nodes", []))
            exp_links = set(exp.get("links", []))
            got_nodes = set(boxes.keys())
            for n in sorted(exp_nodes - got_nodes):
                problems.append(f"G0 missing node {n}")
            for n in sorted(got_nodes - exp_nodes):
                problems.append(f"G0 unexpected node {n}")
            got_links = set()
            for l in link_list:
                # data-link value: "A:iface↔B:iface"
                a = l.split(":")[0]
                b = l.split("↔")[1].strip().split(":")[0]
                got_links.add(tuple(sorted((a, b))))
            exp_pairs = set()
            for l in exp_links:
                a = l.split(":")[0]
                b = l.split("↔")[1].strip().split(":")[0]
                exp_pairs.add(tuple(sorted((a, b))))
            for p in sorted(exp_pairs - got_links):
                problems.append(f"G0 missing link {p}")
            for p in sorted(got_links - exp_pairs):
                problems.append(f"G0 unexpected link {p}")

        # G1 canvas bounds
        for name, (cx, cy, kind, hw, hh) in boxes.items():
            if cx - hw < 0 or cx + hw > VIEW_W or cy - hh < 0 or cy + hh > VIEW_H:
                problems.append(f"G1 {name} out of bounds ({cx:.0f},{cy:.0f})")

        # G2 node overlaps (true box intersection for rect/rect, center
        # distance vs sum of radii for circle/circle, approximate for mixed)
        names = list(boxes.items())
        for i in range(len(names)):
            for j in range(i + 1, len(names)):
                n1, b1 = names[i]
                n2, b2 = names[j]
                if n1.startswith("@") or n2.startswith("@"):
                    continue
                def box_overlap(b1, b2):
                    # returns True if the two node footprints intersect
                    # (b entries: cx, cy, kind, hw, hh where hw/hh are
                    # half-extents already)
                    if b1[2] == "rect" and b2[2] == "rect":
                        dx = abs(b1[0] - b2[0])
                        dy = abs(b1[1] - b2[1])
                        return dx < b1[3] + b2[3] and dy < b1[4] + b2[4]
                    # circle cases: use center distance vs (r + half-extent)
                    dx = b1[0] - b2[0]
                    dy = b1[1] - b2[1]
                    d2 = dx * dx + dy * dy
                    if b1[2] == "circle" and b2[2] == "circle":
                        return d2 < (b1[3] + b2[3]) ** 2
                    # circle + rect: distance from circle center to rect
                    # clamped to the rect box, vs radius
                    if b1[2] == "circle":
                        circle, rect = b1, b2
                    else:
                        circle, rect = b2, b1
                    cx = max(rect[0] - rect[3], min(circle[0], rect[0] + rect[3]))
                    cy = max(rect[1] - rect[4], min(circle[1], rect[1] + rect[4]))
                    return (circle[0] - cx) ** 2 + (circle[1] - cy) ** 2 < circle[3] ** 2
                if box_overlap(b1, b2):
                    problems.append(f"G2 {n1} overlaps {n2}")

        # G3 links endpoints present
        for link in link_list:
            a = link.split(":")[0]
            b = link.split("↔")[1].strip().split(":")[0]
            if a not in boxes and not any(k == a for k in boxes):
                problems.append(f"G3 link endpoint {a} missing node")
            if b not in boxes and not any(k == b for k in boxes):
                problems.append(f"G3 link endpoint {b} missing node")

        # G4 chips near owner
        owner_pos = {}
        for name, (cx, cy, _, hw, hh) in boxes.items():
            owner_pos[name] = (cx, cy)
        for cname, cx, cy in chip_list:
            if cname not in owner_pos:
                problems.append(f"G4 chip for unknown node {cname}")
                continue
            ox, oy = owner_pos[cname]
            d = ((cx - ox) ** 2 + (cy - oy) ** 2) ** 0.5
            # chip sits just outside the node edge + 24px offset; a 140x60 rect
            # gives ~94px from center. Allow up to 120 (generous, catches
            # floating chips without false-flagging correct edge placement).
            if d > 120:
                problems.append(f"G4 chip {cname} too far from owner (d={d:.0f})")

        # G5 chip overlaps — true rect overlap (chips are 42x18; vertical
        # separation >= 18px or horizontal >= 42px is clean)
        for i in range(len(chip_list)):
            for j in range(i + 1, len(chip_list)):
                _, ax, ay = chip_list[i]
                _, bx, by = chip_list[j]
                if abs(ax - bx) < 42 and abs(ay - by) < 18:
                    problems.append(f"G5 chips overlap ({chip_list[i][0]},{chip_list[j][0]})")

        # G7 name fits node
        for name, (cx, cy, kind, hw, hh) in boxes.items():
            if name.startswith("@"):
                continue
            if len(name) * 9 > hw * 2:
                problems.append(f"G7 name {name} may overflow ({len(name)} chars)")

        status = "PASS" if not problems else f"FAIL ({len(problems)})"
        if problems:
            fails += 1
        print(f"Lab {lab:2d} {status}")
        for p in problems[:6]:
            print(f"      {p}")
        if len(problems) > 6:
            print(f"      ... and {len(problems)-6} more")
    print(f"\n{'ALL PASS' if fails == 0 else f'{fails} LABS WITH ISSUES'}")
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
